//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSFlow.Helpers.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MSFlow.Helpers.Resources.MainResources", typeof(MainResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //adj-navigation[@id=&apos;main-navigation&apos;]//a[contains(@href,&apos;Aviator&apos;)].
        /// </summary>
        internal static string DesktopHeaderNavigationAviator {
            get {
                return ResourceManager.GetString("DesktopHeaderNavigationAviator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //adj-aviator//span[contains(@class,&apos;aviator&apos;)].
        /// </summary>
        internal static string MobileAviatorPlayButton {
            get {
                return ResourceManager.GetString("MobileAviatorPlayButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[@data-id=&apos;mobile-login&apos;].
        /// </summary>
        internal static string MobileHeaderLoginButton {
            get {
                return ResourceManager.GetString("MobileHeaderLoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@data-id=&apos;mobile-header-navigation&apos;]/a[contains(@href,&apos;Aviator&apos;)].
        /// </summary>
        internal static string MobileHeaderNavigationAviator {
            get {
                return ResourceManager.GetString("MobileHeaderNavigationAviator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@data-id=&apos;mobile-header-navigation&apos;]/a[contains(@href,&apos;/Poker&apos;)].
        /// </summary>
        internal static string MobileHeaderNavigationPoker {
            get {
                return ResourceManager.GetString("MobileHeaderNavigationPoker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@data-id=&apos;mobile-header-navigation&apos;]/a[contains(@href,&apos;/Games&apos;)].
        /// </summary>
        internal static string MobileHeaderNavigationTableGames {
            get {
                return ResourceManager.GetString("MobileHeaderNavigationTableGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@data-id=&apos;mobile-header-navigation&apos;]/a[contains(@href,&apos;TurboGames&apos;)].
        /// </summary>
        internal static string MobileHeaderNavigationTurboGames {
            get {
                return ResourceManager.GetString("MobileHeaderNavigationTurboGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //span[@data-id=&apos;mobile-username&apos;].
        /// </summary>
        internal static string MobileHeaderUsernameText {
            get {
                return ResourceManager.GetString("MobileHeaderUsernameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //span[@id=&apos;acc-layer-dropdown&apos;]/../div/span.
        /// </summary>
        internal static string MobileHeaderVerifiedCheckmark {
            get {
                return ResourceManager.GetString("MobileHeaderVerifiedCheckmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //button[@data-id=&apos;mobile-login-btn&apos;].
        /// </summary>
        internal static string MobileLoginFormLoginButton {
            get {
                return ResourceManager.GetString("MobileLoginFormLoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@data-id=&apos;password&apos;].
        /// </summary>
        internal static string MobileLoginFormPasswordInput {
            get {
                return ResourceManager.GetString("MobileLoginFormPasswordInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@data-id=&apos;username&apos;].
        /// </summary>
        internal static string MobileLoginFormUsernameInput {
            get {
                return ResourceManager.GetString("MobileLoginFormUsernameInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //adj-poker//span[contains(@class,&apos;poker&apos;)].
        /// </summary>
        internal static string MobilePlayPokerButton {
            get {
                return ResourceManager.GetString("MobilePlayPokerButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //adj-span-item/span[contains(@class,&apos;table-games&apos;)].
        /// </summary>
        internal static string MobileTableBackgammonButton {
            get {
                return ResourceManager.GetString("MobileTableBackgammonButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //span[contains(@class,&apos;bura&apos;)].
        /// </summary>
        internal static string MobileTableBuraButton {
            get {
                return ResourceManager.GetString("MobileTableBuraButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //span[contains(@class,&apos;dominoes&apos;)].
        /// </summary>
        internal static string MobileTableDominoesButton {
            get {
                return ResourceManager.GetString("MobileTableDominoesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //span[contains(@class,&apos;seka&apos;)].
        /// </summary>
        internal static string MobileTableSekaButton {
            get {
                return ResourceManager.GetString("MobileTableSekaButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //adj-span-item/span[contains(@class,&apos;table-games&apos;)].
        /// </summary>
        internal static string MobileTurboDiceButton {
            get {
                return ResourceManager.GetString("MobileTurboDiceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //span[contains(@class,&apos;goal&apos;)].
        /// </summary>
        internal static string MobileTurboGoalButton {
            get {
                return ResourceManager.GetString("MobileTurboGoalButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //span[contains(@class,&apos;hilo&apos;)].
        /// </summary>
        internal static string MobileTurboHiloButton {
            get {
                return ResourceManager.GetString("MobileTurboHiloButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //span[contains(@class,&apos;mines&apos;)].
        /// </summary>
        internal static string MobileTurboMinesButton {
            get {
                return ResourceManager.GetString("MobileTurboMinesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //adj-span-item/span[contains(@class,&apos;live-casino&apos;)].
        /// </summary>
        internal static string MobileTurboMiniRouletteButton {
            get {
                return ResourceManager.GetString("MobileTurboMiniRouletteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //span[contains(@class,&apos;plinko&apos;)].
        /// </summary>
        internal static string MobileTurboPlinkoButton {
            get {
                return ResourceManager.GetString("MobileTurboPlinkoButton", resourceCulture);
            }
        }
    }
}
